global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi_app"
    static_configs:
      - targets: ["fastapi_app:8000"]

  - job_name: "celery_exporter"
    static_configs:
      - targets: ["celery_exporter:9808"]
